# Generated by Django 3.0.8 on 2021-07-07 00:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meal_time',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Desayuno'), (2, 'Comida'), (3, 'Cena'), (4, 'After')], default=2),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], default=3),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dessert',
            field=core.models.CapitalField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='main_dish',
            field=core.models.CapitalField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='side_dish',
            field=core.models.CapitalField(max_length=255),
        ),
    ]
