# Generated by Django 3.0.8 on 2021-07-07 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210707_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='added_by_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
