# Generated by Django 3.0.8 on 2021-07-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210707_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='preparation_day',
            new_name='preparation_date',
        ),
    ]
