# Generated by Django 3.0.8 on 2021-07-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210707_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='day',
            new_name='weekday',
        ),
    ]
