# Generated by Django 3.0.8 on 2021-07-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210708_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], default=5),
        ),
    ]
