# Generated by Django 3.0.8 on 2021-07-10 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_menuselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], default=6),
        ),
        migrations.AlterField(
            model_name='menuselection',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Menu'),
        ),
    ]
