# Generated by Django 3.0.8 on 2021-07-10 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210710_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='added_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
